"""Cloud Run entrypoint: exposes /run for Cloud Scheduler to trigger the Job
Search Pipeline, a review UI at /, and /health for uptime checks.

Local dev:
    uvicorn main:app --reload
    curl -X POST localhost:8080/run

Interactive demo instead (drive the per-job evaluator by hand in a browser):
    adk web .

Auth: the service is deployed --no-allow-unauthenticated, so Cloud Run IAM
rejects unauthenticated requests before they reach this process, and Cloud
Scheduler invokes /run with an OIDC token. RUN_AUTH_TOKEN adds a second gate
on the endpoints that spend money, for the case where the service is ever
made public.
"""
from __future__ import annotations

import hmac
import uuid
from dataclasses import asdict
from typing import Literal
from urllib.parse import quote

from fastapi import Depends, FastAPI, Form, Header, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from pydantic import BaseModel

from career_agent import (
    board_scout, config, matching, pipeline, profile_ui, quickadd, resume_render, review_groups, webui,
)
from career_agent.schemas import TailoredResume
from career_agent.storage import firestore_store
from career_agent.tools import job_tools

app = FastAPI()


def require_run_token(x_run_token: str = Header(default="")) -> None:
    """Guards the endpoints that spend money.

    A no-op unless RUN_AUTH_TOKEN is set. Cloud Run IAM is the real gate when
    the service is deployed --no-allow-unauthenticated; this only matters if
    the service is ever made public, where an open /run means strangers
    spending your Vertex budget. Compared with compare_digest so a wrong token
    cannot be recovered a character at a time from response timings.
    """
    if not config.RUN_AUTH_TOKEN:
        return
    if not hmac.compare_digest(x_run_token, config.RUN_AUTH_TOKEN):
        raise HTTPException(status_code=401, detail="Missing or invalid X-Run-Token.")


@app.get("/health")
def health():
    """Liveness probe.

    NOT /healthz: on Cloud Run that path is swallowed by the Google frontend,
    which returns its own 404 without the request ever reaching the container.
    Verified in production -- every other path served normally while /healthz
    404'd both authenticated and not.
    """
    return {"status": "ok"}


@app.get("/", response_class=HTMLResponse)
def review_ui(status: str = "matched", queued: int = 0, error: str = ""):
    """Read-only review page: matched jobs, their JD links, and why they matched.

    Read-only on purpose. The guardrail this project is built around is that a
    human performs the actual apply/send, so this page links out to the posting
    rather than submitting anything.
    """
    return webui.render(status, queued=bool(queued), error=error)


@app.get("/profile", response_class=HTMLResponse)
def profile_form(saved: int = 0, error: str = ""):
    """Editor for the fields the agent reads."""
    return profile_ui.render(config.load_candidate_profile(), saved=bool(saved), error=error)


@app.post("/profile")
async def save_profile(request: Request):
    """Saves the profile to Firestore and invalidates the cached copy.

    Parsed from the form generated by profile_ui.FIELDS rather than a fixed
    signature, so adding a field to the profile does not require editing this
    handler and silently dropping the new value.
    """
    form = await request.form()
    data: dict = {}
    for name, _, kind, _ in profile_ui.FIELDS:
        raw = (form.get(name) or "").strip()
        if kind == "bool":
            data[name] = bool(form.get(name))
        elif kind == "lines":
            data[name] = [line.strip() for line in raw.splitlines() if line.strip()]
        elif kind == "int":
            # Blank means "no floor", which is not the same as zero.
            data[name] = int(raw) if raw.lstrip("-").isdigit() else None
        elif name == "writing_voice_samples":
            data[name] = [p.strip() for p in raw.split("\n\n") if p.strip()]
        else:
            data[name] = raw

    if not data.get("target_titles"):
        return RedirectResponse(
            "/profile?error=" + quote("At least one target title is required; it drives the pre-filter."),
            status_code=303,
        )
    if not data.get("resume_master_text"):
        return RedirectResponse(
            "/profile?error=" + quote("The master resume cannot be empty; every draft is built from it."),
            status_code=303,
        )

    # Preserve fields this legacy HTML form does not know about. The file is
    # the seed when nothing has been saved yet, so a first save here does not
    # drop everything the form has no input for.
    existing = firestore_store.get_profile() or asdict(config.load_candidate_profile())
    # allowed_locations is the only location field this form has, and the
    # structured preferences outrank it when the agent reads the profile.
    # Rebuilding them keeps an edit here from appearing to work and changing
    # nothing; the work mode saved per location on the settings page survives.
    data["location_preferences"] = matching.preferences_from_allowed_locations(
        data.get("allowed_locations") or [],
        existing.get("location_preferences") or [],
    )
    firestore_store.save_profile({**existing, **data})
    config.invalidate_profile_cache()
    return RedirectResponse("/profile?saved=1", status_code=303)


@app.get("/resume", response_class=HTMLResponse)
def tailored_resume(job_id: str):
    """The tailored resume for one job, as a printable document.

    Served as HTML rather than a generated PDF so it needs no rendering
    dependency in the container: the browser's Print -> Save as PDF produces
    the file to attach, and the print stylesheet drops the on-screen controls.
    """
    app_doc = firestore_store.get_application(job_id)
    if not app_doc:
        raise HTTPException(status_code=404, detail="No application for that job_id.")
    resume = (
        app_doc.get("edited_tailored_resume")
        if app_doc.get("edited_tailored_resume") is not None
        else app_doc.get("tailored_resume")
    )
    if not resume:
        raise HTTPException(
            status_code=404,
            detail="No tailored resume for this job. It was drafted before resumes were generated.",
        )
    profile = config.load_candidate_profile()
    return resume_render.render(
        resume,
        name=profile.full_name,
        contact_line=profile.contact_line,
        job_title=app_doc.get("title", ""),
        company=app_doc.get("company", ""),
    )


def _set_status_across_group(job_id: str, status: str) -> list[str]:
    """Applies a status to every posting on the same grouped review card.

    Both review surfaces render one card per (company, title) but send the id
    of a single underlying application. Resolving the rest here, rather than
    asking each UI to enumerate them, is what keeps a click from leaving the
    duplicate postings behind in the previous tab.
    """
    # Skipped applications are deliberately excluded: they live in their own
    # tab and were never part of the card the human acted on.
    visible = firestore_store.get_applications_by_status(["matched", "drafted", "applied"])
    job_ids = review_groups.group_member_ids(visible, job_id)
    for member_id in job_ids:
        firestore_store.set_application_status(member_id, status)
    return job_ids


@app.post("/applications/status")
def set_status(job_id: str = Form(...), status: str = Form(...)):
    """Marks a job applied (or back to drafted); redirects to the review page."""
    if status not in ("applied", "drafted"):
        raise HTTPException(status_code=400, detail="status must be 'applied' or 'drafted'.")
    _set_status_across_group(job_id, status)
    return RedirectResponse(f"/?status={'applied' if status == 'applied' else 'matched'}", status_code=303)


@app.get("/api/jobs")
def api_jobs(status: str = "matched"):
    """The same data as JSON, for anything that wants to consume it directly."""
    statuses = ["matched", "drafted"] if status == "matched" else [status]
    applications = firestore_store.get_applications_by_status(statuses)
    return {"status": status, "jobs": review_groups.group_applications(applications)}


class QuickAddRequest(BaseModel):
    url: str = ""
    text: str = ""
    title: str = ""
    company: str = ""


class ApplicationStatusRequest(BaseModel):
    job_id: str
    status: str


class MaterialEditRequest(BaseModel):
    job_id: str
    material_type: Literal["cover_letter", "tailored_resume"]
    cover_letter: str | None = None
    tailored_resume: TailoredResume | None = None
    reset: bool = False


class LocationPreferenceRequest(BaseModel):
    location: str
    work_mode: Literal["onsite", "remote", "both"]


class SearchPreferencesRequest(BaseModel):
    target_titles: list[str]
    location_preferences: list[LocationPreferenceRequest]
    needs_visa_sponsorship: bool


@app.get("/api/profile")
def api_profile():
    """Return the search preferences for the current saved beta profile."""
    profile = config.load_candidate_profile()
    return {
        "target_titles": profile.target_titles,
        "location_preferences": matching.normalized_location_preferences(profile),
        "needs_visa_sponsorship": profile.needs_visa_sponsorship,
    }


@app.put("/api/profile")
def api_save_profile(payload: SearchPreferencesRequest):
    """Update search scope without overwriting resume or drafting fields."""
    titles = list(dict.fromkeys(title.strip() for title in payload.target_titles if title.strip()))
    if not titles:
        raise HTTPException(status_code=400, detail="Add at least one target position.")
    if len(titles) > 15:
        raise HTTPException(status_code=400, detail="You can save up to 15 target positions.")
    if not payload.location_preferences:
        raise HTTPException(status_code=400, detail="Add at least one location preference.")
    if len(payload.location_preferences) > matching.MAX_LOCATION_PREFERENCES:
        raise HTTPException(
            status_code=400,
            detail=f"You can save up to {matching.MAX_LOCATION_PREFERENCES} location preferences.",
        )
    if any(not item.location.strip() for item in payload.location_preferences):
        raise HTTPException(status_code=400, detail="Location names cannot be empty.")

    # Same normalizer the agent reads through, so what is stored is what the
    # pre-filter will actually apply.
    locations = matching.validated_location_preferences(
        [{"location": item.location, "work_mode": item.work_mode} for item in payload.location_preferences]
    )

    profile = config.load_candidate_profile()
    existing = firestore_store.get_profile() or asdict(profile)
    updated = {
        **existing,
        "target_titles": titles,
        "location_preferences": locations,
        "allowed_locations": [item["location"] for item in locations],
        "remote_only": all(item["work_mode"] == "remote" for item in locations),
        "needs_visa_sponsorship": payload.needs_visa_sponsorship,
    }
    # Validate the merged document before making it authoritative.
    config._profile_from_dict(updated)
    firestore_store.save_profile(updated)
    config.invalidate_profile_cache()
    return {
        "target_titles": titles,
        "location_preferences": locations,
        "needs_visa_sponsorship": payload.needs_visa_sponsorship,
    }


async def _queue_quick_add(url: str, text: str, title: str, company: str) -> str:
    async with job_tools._client() as client:
        job = await quickadd.build(url=url, text=text, title=title, company=company, client=client)
    firestore_store.enqueue_quick_add(job)
    return job.job_id


@app.post("/api/quick-add", dependencies=[Depends(require_run_token)])
async def api_quick_add(payload: QuickAddRequest):
    """Queues one user-supplied posting for the next run.

    Paste the posting text for anything on LinkedIn/Indeed/Glassdoor/Wellfound;
    a Greenhouse, Lever or Ashby URL is resolved through its public API. See
    career_agent/quickadd.py for why the distinction exists.
    """
    try:
        job_id = await _queue_quick_add(payload.url, payload.text, payload.title, payload.company)
    except quickadd.QuickAddError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    return {"queued": job_id, "note": "Evaluated on the next POST /run."}


@app.post("/api/applications/status")
def api_application_status(payload: ApplicationStatusRequest):
    """Updates the human-owned application status for the separate web UI."""
    if payload.status not in ("applied", "drafted"):
        raise HTTPException(status_code=400, detail="status must be 'applied' or 'drafted'.")
    job_ids = _set_status_across_group(payload.job_id, payload.status)
    return {"job_id": payload.job_id, "job_ids": job_ids, "status": payload.status}


@app.get("/api/materials")
def api_materials(job_id: str):
    """Returns generated and human-edited drafts for one posting."""
    app_doc = firestore_store.get_application(job_id)
    if not app_doc:
        raise HTTPException(status_code=404, detail="No application for that job_id.")

    generated_cover_letter = app_doc.get("cover_letter")
    generated_resume = app_doc.get("tailored_resume")
    if not generated_cover_letter or not generated_resume:
        raise HTTPException(status_code=404, detail="Application materials are not available.")

    edited_cover_letter = app_doc.get("edited_cover_letter")
    edited_resume = app_doc.get("edited_tailored_resume")
    return {
        "job_id": job_id,
        "title": app_doc.get("title", ""),
        "company": app_doc.get("company", ""),
        "generated_cover_letter": generated_cover_letter,
        "edited_cover_letter": edited_cover_letter,
        "effective_cover_letter": (
            edited_cover_letter if edited_cover_letter is not None else generated_cover_letter
        ),
        "cover_letter_edited_at": app_doc.get("cover_letter_edited_at"),
        "generated_tailored_resume": generated_resume,
        "edited_tailored_resume": edited_resume,
        "effective_tailored_resume": edited_resume if edited_resume is not None else generated_resume,
        "tailored_resume_edited_at": app_doc.get("tailored_resume_edited_at"),
    }


@app.put("/api/materials")
def api_save_material(payload: MaterialEditRequest):
    """Saves a human revision or restores the generated draft."""
    if not firestore_store.get_application(payload.job_id):
        raise HTTPException(status_code=404, detail="No application for that job_id.")

    if payload.reset:
        firestore_store.save_material_edit(payload.job_id, payload.material_type, None)
        return {"job_id": payload.job_id, "material_type": payload.material_type, "edited": False}

    if payload.material_type == "cover_letter":
        value = (payload.cover_letter or "").strip()
        if not value:
            raise HTTPException(status_code=400, detail="Cover letter cannot be empty.")
    else:
        if payload.tailored_resume is None:
            raise HTTPException(status_code=400, detail="Tailored resume is required.")
        value = payload.tailored_resume.model_dump()

    firestore_store.save_material_edit(payload.job_id, payload.material_type, value)
    return {"job_id": payload.job_id, "material_type": payload.material_type, "edited": True}


@app.post("/quick-add")
async def quick_add_form(
    url: str = Form(""),
    text: str = Form(""),
    title: str = Form(""),
    company: str = Form(""),
):
    """Form target for the review UI's paste box; redirects back to the page."""
    try:
        await _queue_quick_add(url, text, title, company)
    except quickadd.QuickAddError as e:
        return RedirectResponse(f"/?status=matched&error={quote(str(e))}", status_code=303)
    return RedirectResponse("/?status=matched&queued=1", status_code=303)


@app.post("/run", dependencies=[Depends(require_run_token)])
async def run_pipeline_endpoint(max_jobs: int | None = None, registry_only: bool = False):
    """Runs one full pass of the Job Search Pipeline.

    The control flow lives in career_agent/pipeline.py as ordinary Python; the
    model is called once per job to judge it and once more per match to draft
    materials. Firestore, not session state, is what makes runs idempotent, so
    nothing here needs to persist between requests.
    """
    if max_jobs is not None and not 1 <= max_jobs <= config.MAX_JOBS_PER_RUN:
        raise HTTPException(status_code=400, detail=f"max_jobs must be between 1 and {config.MAX_JOBS_PER_RUN}.")
    return await pipeline.run_once(
        uuid.uuid4().hex[:8], max_jobs=max_jobs, registry_only=registry_only
    )


@app.post("/discover-boards", dependencies=[Depends(require_run_token)])
async def discover_boards(max_candidates: int | None = None):
    """Run one bounded Board Scout pass; only API-validated boards are stored."""
    if max_candidates is not None and not 1 <= max_candidates <= 12:
        raise HTTPException(status_code=400, detail="max_candidates must be between 1 and 12.")
    return await board_scout.run_once(max_candidates=max_candidates)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)
